// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoTest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace test_proto {

  /// <summary>Holder for reflection information generated from ProtoTest.proto</summary>
  public static partial class ProtoTestReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoTest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoTestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Qcm90b1Rlc3QucHJvdG8SCnRlc3RfcHJvdG8iYwoGUmVzUmVzEg4KBmlk",
            "X2tleRgBIAEoBRIPCgdjb21tZW50GAIgASgJEhEKCWhpZ2hfcGF0aBgDIAEo",
            "CRITCgttaWRkbGVfcGF0aBgEIAEoCRIQCghsb3dfcGF0aBgFIAEoCSLjAQoL",
            "UmVzUmVzQXJyYXkSIQoFaXRlbXMYASADKAsyEi50ZXN0X3Byb3RvLlJlc1Jl",
            "cxIjCgV0ZWFtcxgCIAMoDjIULnRlc3RfcHJvdG8uVGVhbUZsYWcSQQoObWFw",
            "X2ludDMyX3RlYW0YAyADKAsyKS50ZXN0X3Byb3RvLlJlc1Jlc0FycmF5Lk1h",
            "cEludDMyVGVhbUVudHJ5GkkKEU1hcEludDMyVGVhbUVudHJ5EgsKA2tleRgB",
            "IAEoBRIjCgV2YWx1ZRgCIAEoDjIULnRlc3RfcHJvdG8uVGVhbUZsYWc6AjgB",
            "Kl0KCFRlYW1GbGFnEhIKDlRFQU1fRkxBR19OT05FEAASFAoQVEVBTV9GTEFH",
            "X1RFQU1fQRABEhQKEFRFQU1fRkxBR19URUFNX0IQAhIRCg1URUFNX0ZMQUdf",
            "TUFYEANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::test_proto.TeamFlag), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::test_proto.ResRes), global::test_proto.ResRes.Parser, new[]{ "id_key", "comment", "high_path", "middle_path", "low_path" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::test_proto.ResResArray), global::test_proto.ResResArray.Parser, new[]{ "items", "teams", "map_int32_team" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 队伍标识
  /// </summary>
  public enum TeamFlag {
    [pbr::OriginalName("TEAM_FLAG_NONE")] None = 0,
    /// <summary>
    /// 队伍A
    /// </summary>
    [pbr::OriginalName("TEAM_FLAG_TEAM_A")] TeamA = 1,
    /// <summary>
    /// 队伍B
    /// </summary>
    [pbr::OriginalName("TEAM_FLAG_TEAM_B")] TeamB = 2,
    [pbr::OriginalName("TEAM_FLAG_MAX")] Max = 3,
  }

  #endregion

  #region Messages
  public sealed partial class ResRes : pb::IMessage<ResRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResRes> _parser = new pb::MessageParser<ResRes>(() => new ResRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::test_proto.ProtoTestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResRes(ResRes other) : this() {
      id_key_ = other.id_key_;
      comment_ = other.comment_;
      high_path_ = other.high_path_;
      middle_path_ = other.middle_path_;
      low_path_ = other.low_path_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResRes Clone() {
      return new ResRes(this);
    }

    /// <summary>Field number for the "id_key" field.</summary>
    public const int id_keyFieldNumber = 1;
    private int id_key_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int id_key {
      get { return id_key_; }
      set {
        id_key_ = value;
      }
    }

    /// <summary>Field number for the "comment" field.</summary>
    public const int commentFieldNumber = 2;
    private string comment_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string comment {
      get { return comment_; }
      set {
        comment_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "high_path" field.</summary>
    public const int high_pathFieldNumber = 3;
    private string high_path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string high_path {
      get { return high_path_; }
      set {
        high_path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "middle_path" field.</summary>
    public const int middle_pathFieldNumber = 4;
    private string middle_path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string middle_path {
      get { return middle_path_; }
      set {
        middle_path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "low_path" field.</summary>
    public const int low_pathFieldNumber = 5;
    private string low_path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string low_path {
      get { return low_path_; }
      set {
        low_path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (id_key != other.id_key) return false;
      if (comment != other.comment) return false;
      if (high_path != other.high_path) return false;
      if (middle_path != other.middle_path) return false;
      if (low_path != other.low_path) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (id_key != 0) hash ^= id_key.GetHashCode();
      if (comment.Length != 0) hash ^= comment.GetHashCode();
      if (high_path.Length != 0) hash ^= high_path.GetHashCode();
      if (middle_path.Length != 0) hash ^= middle_path.GetHashCode();
      if (low_path.Length != 0) hash ^= low_path.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (id_key != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(id_key);
      }
      if (comment.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(comment);
      }
      if (high_path.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(high_path);
      }
      if (middle_path.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(middle_path);
      }
      if (low_path.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(low_path);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (id_key != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(id_key);
      }
      if (comment.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(comment);
      }
      if (high_path.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(high_path);
      }
      if (middle_path.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(middle_path);
      }
      if (low_path.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(low_path);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (id_key != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(id_key);
      }
      if (comment.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(comment);
      }
      if (high_path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(high_path);
      }
      if (middle_path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(middle_path);
      }
      if (low_path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(low_path);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResRes other) {
      if (other == null) {
        return;
      }
      if (other.id_key != 0) {
        id_key = other.id_key;
      }
      if (other.comment.Length != 0) {
        comment = other.comment;
      }
      if (other.high_path.Length != 0) {
        high_path = other.high_path;
      }
      if (other.middle_path.Length != 0) {
        middle_path = other.middle_path;
      }
      if (other.low_path.Length != 0) {
        low_path = other.low_path;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            id_key = input.ReadInt32();
            break;
          }
          case 18: {
            comment = input.ReadString();
            break;
          }
          case 26: {
            high_path = input.ReadString();
            break;
          }
          case 34: {
            middle_path = input.ReadString();
            break;
          }
          case 42: {
            low_path = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            id_key = input.ReadInt32();
            break;
          }
          case 18: {
            comment = input.ReadString();
            break;
          }
          case 26: {
            high_path = input.ReadString();
            break;
          }
          case 34: {
            middle_path = input.ReadString();
            break;
          }
          case 42: {
            low_path = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ResResArray : pb::IMessage<ResResArray>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResResArray> _parser = new pb::MessageParser<ResResArray>(() => new ResResArray());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResResArray> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::test_proto.ProtoTestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResResArray() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResResArray(ResResArray other) : this() {
      items_ = other.items_.Clone();
      teams_ = other.teams_.Clone();
      map_int32_team_ = other.map_int32_team_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResResArray Clone() {
      return new ResResArray(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int itemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::test_proto.ResRes> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::test_proto.ResRes.Parser);
    private readonly pbc::RepeatedField<global::test_proto.ResRes> items_ = new pbc::RepeatedField<global::test_proto.ResRes>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::test_proto.ResRes> items {
      get { return items_; }
    }

    /// <summary>Field number for the "teams" field.</summary>
    public const int teamsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::test_proto.TeamFlag> _repeated_teams_codec
        = pb::FieldCodec.ForEnum(18, x => (int) x, x => (global::test_proto.TeamFlag) x);
    private readonly pbc::RepeatedField<global::test_proto.TeamFlag> teams_ = new pbc::RepeatedField<global::test_proto.TeamFlag>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::test_proto.TeamFlag> teams {
      get { return teams_; }
    }

    /// <summary>Field number for the "map_int32_team" field.</summary>
    public const int map_int32_teamFieldNumber = 3;
    private static readonly pbc::MapField<int, global::test_proto.TeamFlag>.Codec _map_map_int32_team_codec
        = new pbc::MapField<int, global::test_proto.TeamFlag>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForEnum(16, x => (int) x, x => (global::test_proto.TeamFlag) x, global::test_proto.TeamFlag.None), 26);
    private readonly pbc::MapField<int, global::test_proto.TeamFlag> map_int32_team_ = new pbc::MapField<int, global::test_proto.TeamFlag>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::test_proto.TeamFlag> map_int32_team {
      get { return map_int32_team_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResResArray);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResResArray other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      if(!teams_.Equals(other.teams_)) return false;
      if (!map_int32_team.Equals(other.map_int32_team)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      hash ^= teams_.GetHashCode();
      hash ^= map_int32_team.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      teams_.WriteTo(output, _repeated_teams_codec);
      map_int32_team_.WriteTo(output, _map_map_int32_team_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      teams_.WriteTo(ref output, _repeated_teams_codec);
      map_int32_team_.WriteTo(ref output, _map_map_int32_team_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      size += teams_.CalculateSize(_repeated_teams_codec);
      size += map_int32_team_.CalculateSize(_map_map_int32_team_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResResArray other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      teams_.Add(other.teams_);
      map_int32_team_.Add(other.map_int32_team_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
          case 18:
          case 16: {
            teams_.AddEntriesFrom(input, _repeated_teams_codec);
            break;
          }
          case 26: {
            map_int32_team_.AddEntriesFrom(input, _map_map_int32_team_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
          case 18:
          case 16: {
            teams_.AddEntriesFrom(ref input, _repeated_teams_codec);
            break;
          }
          case 26: {
            map_int32_team_.AddEntriesFrom(ref input, _map_map_int32_team_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
